IgniteUI/igniteui-docfx-template

- styles/sample-iframe-handler.js
> set iframe body overflow

- styles/sample-iframe-handler.js
> remove setting overflow: hideen to the iframe body

- partials/logo.tmpl.partial
- styles/css/main.css
- styles/sass/partials/_navbar.scss
> Dynamic navbar title

- styles/docfx.js
> Fixed resources file path

- layout/_master.tmpl
- resources/resources-en.json
- resources/resources-ja.json
- styles/docfx.js
> Fixed resources

- layout/_master.tmpl
- partials/infrafoot.ja.tmpl.partial
- partials/infrafoot.tmpl.partial
- partials/infranav.ja.tmpl.partial
- partials/infranav.tmpl.partial
- post-processors/PostProcessors/EnvironmentVariables/preconfig.json
- styles/api-browser.js
> Updated the Infragistics header & footer

- layout/_master.tmpl
- partials/footer.tmpl.partial
- partials/head.tmpl.partial
- post-processors/PostProcessors/EnvironmentVariables/preconfig.json
> Added environment specific GTM container ids.

- partials/li.tmpl.partial
- styles/css/main.css
- styles/docfx.js
- styles/sass/partials/_toc.scss
- toc.extension.js
- toc.html.tmpl
> feat(toc): enable TOC item filtering

- styles/stackblitz-handler.js
> keep the stackblitz button disabled until necessary resources are loaded

- README.md
> Update readme.md with npm version badge

- styles/stackblitz-handler.js
> Fixed StackBlitz not opening

- post-processors/PostProcessors/EnvironmentVariables/preconfig.json
> add url for sass docs

- post-processors/PostProcessors/EnvironmentVariables/preconfig.json
> Changing the environment variables for japanese version.

- partials/infrafoot.ja.tmpl.partial
- partials/infrafoot.kr.tmpl.partial
- partials/infrafoot.tmpl.partial
> Updated KR footer and second EN & JP footer

- post-processors/PostProcessors/EnvironmentVariables/preconfig.json
> Updated Korean Google Analyrics Container Ids

- template/toc.html.tmpl
> Update component search placeholder

- post-processors/PostProcessors/EnvironmentVariables/preconfig.json
> Adding latest to EN, JP and KR links - dev, stage and prod

- template/partials/infranav.ja.tmpl.partial
Closes https://github.com/IgniteUI/igniteui-docfx/issues/816
> Changing Global Nav icon logo for JP verison

- template/partials/head.tmpl.partial
> Remove www prefixes from stylesheet links

- template/partials/themeselect.ja.tmpl.partial
> Localizing theming

- template/bundling.global.json
- template/styles/sample-iframe-handler.js
> Add onload handler for xPlat samples

- template/partials/infranav.kr.tmpl.partial
> Change infranav account link for KR

- post-processors/PostProcessors/EnvironmentVariables/preconfig.json
Closes #116
staging.infragistics.com is now staging.infragistics.local
> Change staging urls

- post-processors/PostProcessors/EnvironmentVariables/preconfig.json
- template/layout/_master.tmpl
> Add variable in each env for dv samples

- post-processors/PostProcessors/EnvironmentVariables/preconfig.json
> Adding temporary variable for Angular dv  api docs base url

- post-processors/PostProcessors/EnvironmentVariables/preconfig.json
- template/bundling.global.json
- template/partials/infranav.kr.tmpl.partial
Update the template to reflect change to the new KR domain -- www.infragistics.co.kr.
> Update KR domains to infragistics.co.kr

- template/toc.extension.js
- template/toc.html.tmpl
> Adding language recognition to toc file

- post-processors/PostProcessors/EnvironmentVariables/preconfig.json
> Creating new environment variable for the lob samples

- template/styles/css/main.css
We resolved this once, please don't change this line anymore :)
> fix(safari): resolving issue with sideaffix overflow

- template/ManagedReference.html.primary.js
- template/bundling.global.json
> Adding language detection for API docs

- template/bundling.global.json
- template/partials/li.tmpl.partial
> Fixing "new_badge" bug

- template/bundling.global.json
- template/partials/infranav.ja.tmpl.partial
- template/partials/infranav.kr.tmpl.partial
- template/partials/infranav.tmpl.partial
> Change main navigation link of UX item

- template/partials/head.tmpl.partial
Closes this [issue](https://github.com/IgniteUI/trial-watermark/issues/73)
> Adding support for custom canonical links

- template/bundling.global.json
- template/toc.html.js
Closes #https://github.com/IgniteUI/igniteui-docfx/issues/2319
> Alphabetize TOC grids items

- template/bundling.global.json
- template/toc.html.js
Closes #IgniteUI/igniteui-docfx#2319
> Alphabetize TOC items

- template/bundling.global.json
- template/toc.html.js
> Refactor alphabetical sorting functionality

- template/partials/head.tmpl.partial
> Changing site icon

- template/bundling.global.json
- template/partials/infranav.ja.tmpl.partial
Update the indigo design price in jp navigation template.
> Update ja navigation price

- src/code-view.js
- src/docfx.js
- template/styles/docfx.css
> Code views during docfx initialization

- gulpfile.js
- src/code-view.js
- src/live-editing-handler.js
- src/styles/partials/_button-link.scss
- src/styles/partials/_code-view.scss
- template/partials/head.tmpl.partial
- template/styles/docfx.css
> Creating cross-platform code view

- src/lazysizes-handler.js
> Fixing lazyloaded handler

- src/docfx.js
Related to # https://github.com/IgniteUI/igniteui-docfx/issues/2637
> Add cta banners-vnext

- src/docfx.js
Related to # IgniteUI/igniteui-docfx#2637
> Add cta banners

- src/docfx.js
- template/partials/head.tmpl.partial
Related to #https://github.com/IgniteUI/igniteui-docfx/issues/2637
> Fix internal paths - vnext

- src/styles/partials/_button-link.scss
- src/styles/partials/_iframe.scss
> Change images relative url

- src/app/services/code-view/angular-code-service.ts
> Change stackblitz form creation

- src/app/services/code-view/angular-code-service.ts
> Enable tsconfig when the sample needs it

- template/partials/infranav.ja.tmpl.partial
- template/partials/infranav.tmpl.partial
> Update EN and JP infranav patial

- src/app/services/rendering/article.ts
> Fix html removal from internal anchors

- src/styles/partials/_affix.scss
> Make affix widht fixed vnext

- src/app/services/rendering/article.ts
> Add GTM paragraph after the first code view in a topic

- src/app/services/router.ts
> Remove html from route when needed

- template/partials/infranav.ja.tmpl.partial
- template/partials/infranav.tmpl.partial
> Navigation html update -vnext

- template/partials/infranav.ja.tmpl.partial
- template/partials/infranav.tmpl.partial
> Navigation html update -master

- template/partials/head.tmpl.partial
This PR should be tested with https://github.com/SlingshotApplication/Documentation/pull/27
Also please try it out with Angular docfx instance.
> Add favicon capability

- src/styles/slingshot/main.scss
- template/layout/_master.tmpl
- template/partials/slingshot/footer.tmpl.partial
- template/partials/slingshot/slingshotfoot.ja.tmpl.partial
- template/partials/slingshot/slingshotfoot.tmpl.partial
> Add Slingshot footer

- src/styles/ignite-ui/_variables.scss
- src/styles/ignite-ui/main.scss
- src/styles/shared/_global.scss
- src/styles/shared/_mixins.scss
- src/styles/shared/_typography.scss
- src/styles/shared/_variables.scss
- src/styles/shared/components/_affix.scss
- src/styles/shared/components/_details.scss
- src/styles/shared/components/_index.scss
- src/styles/shared/components/_main-content.scss
- src/styles/shared/components/_sidenav.scss
- src/styles/shared/components/_table.scss
- src/styles/slingshot/_variables.scss
- src/styles/slingshot/main.scss
> Improve the styles for igniteui docFX template

- src/app/services/rendering/article.ts
Closes https://github.com/IgniteUI/igniteui-docfx-template/issues/342
> Add additional cta banner for angular

- src/app/services/code-view/angular-code-service.ts
> Fix stackblitz/csb buttons without code view

- src/app/services/code-view/angular-code-service.ts
- src/app/services/code-view/code-view.ts
- src/app/types.ts
> Add ability to choose code view editor -master

- src/app/services/utils.ts
> Update lazy load handler

- src/app/services/rendering/toc.ts
- src/app/services/search/lunr-client.ts
- src/styles/shared/components/_sidenav.scss
- src/styles/shared/components/header/_navbar.scss
- template/partials/navbar.tmpl.partial
- template/toc.html.tmpl
> Remain open filtering results and add clearing functionality

- src/app/services/search/lunr-client.ts
- template/partials/navbar.tmpl.partial
- template/toc.html.js
- template/toc.html.tmpl
> Fix search icon hiding and sortable topics check

- src/styles/shared/components/_features.scss
Related to https://github.com/IgniteUI/indigo-design-docfx/pull/552
> Update iframe video styling to make the more fluid/responsive

- template/partials/infranav.tmpl.partial
> Update main navigation

- template/partials/infranav.ja.tmpl.partial
- template/partials/infranav.tmpl.partial
Related to #https://github.com/IgniteUI/igniteui-docfx/issues/2996
> Update appbuilder link

- src/app/services/rendering/article.ts
Part of closing [#4](https://github.com/IgniteUI/app-builder-docfx/issues/4)
> fix(seo-banner): remove undefined platform property

- src/styles/shared/components/header/_navbar.scss
> Reduce framework buttons size

- template/partials/infranav.tmpl.partial
> Add Design System & UI Kits link under under the AppBuilder link

- src/app/services/rendering/article.ts
Related to https://github.com/IgniteUI/igniteui-docfx-template/issues/377
> Change blazor and react cta banner position

- src/app/services/code-view/angular-code-service.ts
Closes [#3263](https://github.com/IgniteUI/igniteui-docfx/issues/3263)
> check explicitly for dv samples

- src/app/services/code-view/common.ts
- src/app/services/rendering/navbar.ts
- src/app/services/router.ts
- src/i18n/constants-en.ts
- src/i18n/constants-jp.ts
- src/styles/ignite-ui/_variables.scss
- src/styles/shared/components/_infranav.scss
- template/conceptual.html.primary.js
- template/partials/helloBar.tmpl.partial
- template/partials/infranav.ja.tmpl.partial
- template/partials/infranav.tmpl.partial
Closes https://github.com/IgniteUI/igniteui-docfx/issues/3276
> V dyulgerov/add download now button master

- src/app/services/navigation.ts
- src/app/services/rendering/navbar.ts
- template/partials/helloBar.tmpl.partial
Related to #https://github.com/IgniteUI/igniteui-docfx/issues/3276
> Remove duplicated hello bar

- src/app/services/rendering/article.ts
- src/styles/shared/components/_infranav.scss
> Set different cta banner links based on localized version

- src/app/services/rendering/navbar.ts
> Fix toc alignment

- README.md
> chore(readme): update file to use newest commands and add setup section - master

- src/styles/shared/components/_sidenav.scss
Close #398 
| Before | After | 
| --- | --- |
|![image](https://user-images.githubusercontent.com/33124382/199707465-1a63210e-68b4-4afd-bb4d-5f75299316d1.png) |![image](https://user-images.githubusercontent.com/33124382/199707492-f6653a7c-6a17-40dc-ae4b-d549e35927ad.png) |
> fix(menu): resolve overlapping of components list - vnext

- src/styles/shared/components/_sidenav.scss
Close #398 
| Before | After | 
| --- | --- |
|![image](https://user-images.githubusercontent.com/33124382/199707465-1a63210e-68b4-4afd-bb4d-5f75299316d1.png) |![image](https://user-images.githubusercontent.com/33124382/199707492-f6653a7c-6a17-40dc-ae4b-d549e35927ad.png) |
> fix(menu): resolve overlapping of components list - master

- src/app/services/code-view/angular-code-service.ts
Close [#3188](https://github.com/IgniteUI/igniteui-angular-samples/issues/3188)
> fix(angular-service): remove query params from file name

- template/partials/slingshot/slingshotfoot.ja.tmpl.partial
- template/partials/slingshot/slingshotfoot.tmpl.partial
> Update copyright date

- template/partials/frameworks.ja.tmpl.partial
- template/partials/frameworks.tmpl.partial
- template/partials/navbar.tmpl.partial
> Add jp frameworks navigation links

- src/app/services/code-view/angular-code-service.ts
Related to #https://github.com/IgniteUI/igniteui-angular-samples/issues/3239
> Handle default sample metadata paths

- src/app/services/code-view/angular-code-service.ts
Related to #https://github.com/IgniteUI/igniteui-angular-samples/issues/3239
> Fix default module samples cors error

- src/app/services/rendering/navbar.ts
> Fix navbar ProductSpinal links

- src/app/services/rendering/toc.ts
> Fix toc resizing

- src/app/services/rendering/article.ts
> Handle blockquote alerts rendering

- src/styles/shared/_shadows.scss
- src/styles/shared/components/_responsive.scss
- src/styles/slingshot/main.scss
> Define default image styles

- src/app/services/rendering/affix.ts
> Handle empty hierarchy affix

- package-lock.json
- package.json
- src/app/services/code-view/code-view.ts
> Add razor tabs highlight support

- template/partials/scripts.tmpl.partial
> Add tass script only for angular instance

- src/styles/ignite-ui/_variables.scss
- src/styles/slingshot/_variables.scss
> Add lighter color for hljs selector

- src/app/services/rendering/toc.ts
> Open toc topics in a new tab on Ctrl + click

- src/app/services/code-view/angular-code-service.ts
- src/app/services/code-view/code-view.ts
- src/app/services/code-view/sharedFiles.ts
Closes #https://github.com/IgniteUI/igniteui-docfx-template/issues/442
> Enable codesandbox live editing button

- src/app/services/code-view/angular-code-service.ts
Related to #https://github.com/IgniteUI/igniteui-docfx/issues/3290
Closes #451 451
> Add correct dv samples path

- src/app/services/rendering/affix.ts
Closes #https://github.com/IgniteUI/igniteui-docfx/issues/3196
> Fix right side affix for mobile devices

- src/app/services/rendering/article.ts
- src/styles/appbuilder/_variables.scss
- src/styles/appbuilder/main.scss
Closes #460
1. Update font sizes
2. Update CTA banner link
3. Fix responsiveness
> Update appbuilder theme font styles and fixes

- src/app/services/rendering/toc.ts
> refactor(template): refactor filtering logic

- src/app/services/rendering/article.ts
- src/styles/shared/_global.scss
Set static images for code-view with attribute set - 'img-sec'. It sepresents image name hosted in [https://static.infragistics.com/marketing/Website/](https://static.infragistics.com/marketing/Website/products/Ignite-UI-for-Angular/ignite-ui-angular-bar-chart-1920x922.png) site. Different images based on the sample are based on different sizes https://static.infragistics.com/marketing/Website/products/Ignite-UI-for-Angular/ignite-ui-angular-bar-chart-1920x922.png
https://static.infragistics.com/marketing/Website/products/Ignite-UI-for-Angular/ignite-ui-angular-bar-chart-1213x498.png
https://static.infragistics.com/marketing/Website/products/Ignite-UI-for-Angular/ignite-ui-angular-bar-chart-843x498.png
https://static.infragistics.com/marketing/Website/products/Ignite-UI-for-Angular/ignite- …
> Improve samples static image display before load

- .github/workflows/node.js.yml
- .github/workflows/npm-publish.yml
- gulpfile.js
- template/conceptual.html.primary.js
- template/partials/appbuilder/appbuilderfoot.tmpl.partial
- template/partials/appbuilder/navbar.tmpl.partial
- template/partials/infrafoot.ja.tmpl.partial
- template/partials/infrafoot.kr.tmpl.partial
- template/partials/infrafoot.tmpl.partial
- template/partials/revealfoot.ja.tmpl.partial
- template/partials/revealfoot.tmpl.partial
- template/partials/slingshot/slingshotfoot.ja.tmpl.partial
- template/partials/slingshot/slingshotfoot.tmpl.partial
Closes #476 
Closes #477
Closes #478
Closes #474
1. Fixing node security vulnerability based on `child_process.spawn` and `child_process.spawnSync` - https://nodejs.org/en/blog/vulnerability/april-2024-security-releases-2
2. Fixed multiple Table of content request made for AB documentation
3. Updated tml partial files with Copyright year
4. Added automatical update copyright year in footer templates
- Added `_currentYear` to `model` in `conceptual.html.primary.js`
- Used `{{_currentYear}}` in the footer template to dynamically display the current year
- Ensures the copyright year updates automatically with each DocFX build
> Update actions node vesion and update templates

- template/partials/head.tmpl.partial
Runtime code to change the header template and include working language items
> fix language bar
